### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by rccoleman** [kalkih/mini-graph-card#237]
I'd like to tinker with this card and I'm unable to build either the v0.8.2 released version or 0.9.0-beta from source based on the instructions in the README.  On both my Ubuntu Linux machine and my MBP I always get the following during the "babel" portion of the build on both 0.8.2 and 0.9.0-beta:

```
rcoleman@rcoleman-linux ~/git/mini-graph-card % npm run build             

> mini-graph-card@0.8.2 build /home/rcoleman/git/mini-graph-card
> npm run lint && npm run rollup && npm run babel


> mini-graph-card@0.8.2 lint /home/rcoleman/git/mini-graph-card
> eslint src/* --ext .js


> mini-graph-card@0.8.2 rollup /home/rcoleman/git/mini-graph-card
> rollup -c


src/main.js → dist/mini-graph-card-bundle.js...
created dist/mini-graph-card-bundle.js in 682ms

> mini-graph-card@0.8.2 babel /home/rcoleman/git/mini-graph-card
> babel dist/mini-graph-card-bundle.js --out-file dist/mini-graph-card-bundle.js

{ TypeError: /home/rcoleman/git/mini-graph-card/dist/mini-graph-card-bundle.js: Cannot read property 'add' of undefined
    at ScopeTracker.addReference (/home/rcoleman/git/mini-graph-card/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:47:34)
    at ReferencedIdentifier (/home/rcoleman/git/mini-graph-card/node_modules/babel-plugin-minify-mangle-names/lib/index.js:196:26)
    at newFn (/home/rcoleman/git/mini-graph-card/node_modules/@babel/traverse/lib/visitors.js:220:17)
    at bfsTraverse (/home/rcoleman/git/mini-graph-card/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:32:43)
    at Mangler.collect (/home/rcoleman/git/mini-graph-card/node_modules/babel-plugin-minify-mangle-names/lib/index.js:229:7)
    at Mangler.run (/home/rcoleman/git/mini-graph-card/node_modules/babel-plugin-minify-mangle-names/lib/index.js:54:12)
    at PluginPass.exit (/home/rcoleman/git/mini-graph-card/node_modules/babel-plugin-minify-mangle-names/lib/index.js:558:19)
    at newFn (/home/rcoleman/git/mini-graph-card/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/rcoleman/git/mini-graph-card/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/rcoleman/git/mini-graph-card/node_modules/@babel/traverse/lib/path/context.js:42:17) code: 'BABEL_TRANSFORM_ERROR' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mini-graph-card@0.8.2 babel: `babel dist/mini-graph-card-bundle.js --out-file dist/mini-graph-card-bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mini-graph-card@0.8.2 babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rcoleman/.npm/_logs/2020-01-12T22_49_36_678Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mini-graph-card@0.8.2 build: `npm run lint && npm run rollup && npm run babel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mini-graph-card@0.8.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rcoleman/.npm/_logs/2020-01-12T22_49_36_694Z-debug.log
```
I'm a novice at this and haven't found anything useful on the web that seems to help.  node and nodejs installed successfully from here: https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/.

**Comment by kalkih** [comment]
Hello,
Not really sure why you get this, was able to reproduce when re-installing all npm packages, might be a bug or a broken package.

Changing the `.babel.rc` file to the following should prevent the error for occurring.
I've pushed the change to the dev branch https://github.com/kalkih/mini-graph-card/commit/709a5ded6fec03501424a15b534f5c733742f00f so run a `git pull` from the dev branch and you should be good to go!

```yaml
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "targets": {
          "esmodules": true
        }
      }
    ],
    ["minify"],
  ],
  "comments": false,
  "plugins": [
    ["@babel/plugin-transform-template-literals"],
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    ["@babel/plugin-proposal-object-rest-spread"],
    ["@babel/plugin-transform-spread"],
    ["iife-wrap"],
  ],
}
```

**Comment by rccoleman** [comment]
That did it!  Thanks for the quick response.
