### ISSUE TITLE
Seeing some errors with mini-graph-card and mini-media-player

### ISSUE THREAD

**Issue by gieljnssns** [kalkih/mini-graph-card#244]
Safari:  ```NotSupportedError: Cannot define multiple custom elements with the same tag name```
```
[Error] NotSupportedError: Cannot define multiple custom elements with the same tag name
	define (mini-graph-card-bundle.js:1:86727)
	(anonieme functie) (mini-graph-card-bundle.js:1:86727)
	(anonieme functie) (mini-graph-card-bundle.js:1:17803)
	(anonieme functie) (mini-graph-card-bundle.js:1:17807)
	Modulecode (mini-graph-card-bundle.js:1:86753)
	evaluate
	moduleEvaluation
[Error] NotSupportedError: Cannot define multiple custom elements with the same tag name
	define (mini-media-player-bundle.js:1:74431)
	(anonieme functie) (mini-media-player-bundle.js:1:74431)
	(anonieme functie) (mini-media-player-bundle.js:1:38445)
	(anonieme functie) (mini-media-player-bundle.js:1:38449)
	Modulecode (mini-media-player-bundle.js:1:91280)
	evaluate
	moduleEvaluation
```
Brave browser:  ```Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mini-graph-card" has already been used with this registry```
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mini-graph-card" has already been used with this registry
    at http://192.168.79.54:8123/community_plugin/mini-graph-card/mini-graph-card-bundle.js:1:86720
    at http://192.168.79.54:8123/community_plugin/mini-graph-card/mini-graph-card-bundle.js:1:17801
    at http://192.168.79.54:8123/community_plugin/mini-graph-card/mini-graph-card-bundle.js:1:17806
    at http://192.168.79.54:8123/community_plugin/mini-graph-card/mini-graph-card-bundle.js:1:86752
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mmp-group-item" has already been used with this registry
    at http://192.168.79.54:8123/community_plugin/mini-media-player/mini-media-player.js:1:68547
    at http://192.168.79.54:8123/community_plugin/mini-media-player/mini-media-player.js:1:33865
    at http://192.168.79.54:8123/community_plugin/mini-media-player/mini-media-player.js:1:33870
    at http://192.168.79.54:8123/community_plugin/mini-media-player/mini-media-player.js:1:83456
```

**Comment by kalkih** [comment]
Hello,
This means your browser is loading and executing the code twice.
Make sure you only got one reference to each card in your `ui-lovelace.yaml` or raw config editor if you're using the GUI editor.
e.g. If you've installed the card manually before and moved to HACS make sure to remove the "old" resource references.

**Comment by gieljnssns** [comment]
> e.g. If you've installed the card manually before and moved to HACS make sure to remove the "old" resource references.

Thanks a lot....
