### ISSUE TITLE
Cannot build - getting BABEL_PARSE_ERROR and ELIFECYCLE error

### ISSUE THREAD

**Issue by u8915055** [kalkih/mini-graph-card#577]
hello,
First off, GREAT module!  I was hoping to do a few customizations of the module so i have cloned the dev branch as instructed and am now trying the build.  For some reason im getting an error when i build it.  Looks like this:

```
mac-mini:mini-graph-card u8915055$  npm run build

> mini-graph-card@0.11.0-dev.4 build
> npm run lint && npm run rollup && npm run babel


> mini-graph-card@0.11.0-dev.4 lint /Users/u8915055/.homeassistant/www/mini-graph-card
> eslint src/* --ext .js


> mini-graph-card@0.11.0-dev.4 rollup /Users/u8915055/.homeassistant/www/mini-graph-card
> rollup -c


src/main.js → dist/mini-graph-card-bundle.js...
created dist/mini-graph-card-bundle.js in 1.4s

> mini-graph-card@0.11.0-dev.4 babel /Users/u8915055/.homeassistant/www/mini-graph-card
> babel dist/mini-graph-card-bundle.js --out-file dist/mini-graph-card-bundle.js

SyntaxError: /Users/u8915055/.homeassistant/www/mini-graph-card/dist/mini-graph-card-bundle.js: Unexpected token (5802:12)

  5800 |     };
  5801 |
> 5802 |     function(){try{(new Date).toLocaleDateString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleDateString(t,{year:"numeric",month:"long",day:"numeric"})}:function(t){return fecha.format(t,"mediumDate")};function(){try{(new Date).toLocaleString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleString(t,{year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"})}:function(t){return fecha.format(t,"haDateTime")};function(){try{(new Date).toLocaleTimeString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleTimeString(t,{hour:"numeric",minute:"2-digit"})}:function(t){return fecha.format(t,"shortTime")};function f$1(e){return e.substr(0,e.indexOf("."))}var _="hass:bookmark",L={alert:"hass:alert",automation:"hass:playlist-play",calendar:"hass:calendar",camera:"hass:video",climate:"hass:thermostat",configurator:"hass:settings",conversation:"hass:text-to-speech",device_tracker:"hass:account",fan:"hass:fan",group:"hass:google-circles-communities",history_graph:"hass:chart-line",homeassistant:"hass:home-assistant",homekit:"hass:home-automation",image_processing:"hass:image-filter-frames",input_boolean:"hass:drawing",input_datetime:"hass:calendar-clock",input_number:"hass:ray-vertex",input_select:"hass:format-list-bulleted",input_text:"hass:textbox",light:"hass:lightbulb",mailbox:"hass:mailbox",notify:"hass:comment-alert",person:"hass:account",plant:"hass:flower",proximity:"hass:apple-safari",remote:"hass:remote",scene:"hass:google-pages",script:"hass:file-document",sensor:"hass:eye",simple_alarm:"hass:bell",sun:"hass:white-balance-sunny",switch:"hass:flash",timer:"hass:timer",updater:"hass:cloud-upload",vacuum:"hass:robot-vacuum",water_heater:"hass:thermometer",weblink:"hass:open-in-new"};function O(e,t){if(e in L)return L[e];switch(e){case"alarm_control_panel":switch(t){case"armed_home":return "hass:bell-plus";case"armed_night":return "hass:bell-sleep";case"disarmed":return "hass:bell-outline";case"triggered":return "hass:bell-ring";default:return "hass:bell"}case"binary_sensor":return t&&"off"===t?"hass:radiobox-blank":"hass:checkbox-marked-circle";case"cover":return "closed"===t?"hass:window-closed":"hass:window-open";case"lock":return t&&"unlocked"===t?"hass:lock-open":"hass:lock";case"media_player":return t&&"off"!==t&&"idle"!==t?"hass:cast-connected":"hass:cast";case"zwave":switch(t){case"dead":return "hass:emoticon-dead";case"sleeping":return "hass:sleep";case"initializing":return "hass:timer-sand";default:return "hass:z-wave"}default:return console.warn("Unable to find icon for domain "+e+" ("+t+")"),_}}var Z={humidity:"hass:water-percent",illuminance:"hass:brightness-5",temperature:"hass:thermometer",pressure:"hass:gauge",power:"hass:flash",signal_strength:"hass:wifi"},$={binary_sensor:function(e){var t=e.state&&"off"===e.state;switch(e.attributes.device_class){case"battery":return t?"hass:battery":"hass:battery-outline";case"cold":return t?"hass:thermometer":"hass:snowflake";case"connectivity":return t?"hass:server-network-off":"hass:server-network";case"door":return t?"hass:door-closed":"hass:door-open";case"garage_door":return t?"hass:garage":"hass:garage-open";case"gas":case"power":case"problem":case"safety":case"smoke":return t?"hass:shield-check":"hass:alert";case"heat":return t?"hass:thermometer":"hass:fire";case"light":return t?"hass:brightness-5":"hass:brightness-7";case"lock":return t?"hass:lock":"hass:lock-open";case"moisture":return t?"hass:water-off":"hass:water";case"motion":return t?"hass:walk":"hass:run";case"occupancy":return t?"hass:home-outline":"hass:home";case"opening":return t?"hass:square":"hass:square-outline";case"plug":return t?"hass:power-plug-off":"hass:power-plug";case"presence":return t?"hass:home-outline":"hass:home";case"sound":return t?"hass:music-note-off":"hass:music-note";case"vibration":return t?"hass:crop-portrait":"hass:vibrate";case"window":return t?"hass:window-closed":"hass:window-open";default:return t?"hass:radiobox-blank":"hass:checkbox-marked-circle"}},cover:function(e){var t="closed"!==e.state;switch(e.attributes.device_class){case"garage":return t?"hass:garage-open":"hass:garage";case"door":return t?"hass:door-open":"hass:door-closed";case"shutter":return t?"hass:window-shutter-open":"hass:window-shutter";case"blind":return t?"hass:blinds-open":"hass:blinds";case"window":return t?"hass:window-open":"hass:window-closed";default:return O("cover",e.state)}},sensor:function(e){var t=e.attributes.device_class;if(t&&t in Z)return Z[t];if("battery"===t){var a=Number(e.state);if(isNaN(a))return "hass:battery-unknown";var r=10*Math.round(a/10);return r>=100?"hass:battery":r<=0?"hass:battery-alert":"hass:battery-"+r}var n=e.attributes.unit_of_measurement;return "°C"===n||"°F"===n?"hass:thermometer":O("sensor")},input_datetime:function(e){return e.attributes.has_date?e.attributes.has_time?O("input_datetime"):"hass:calendar":"hass:clock"}},ee=function(e){if(!e)return _;if(e.attributes.icon)return e.attributes.icon;var t=f$1(e.entity_id);return t in $?$[t](e):O(t,e.state)};
       |             ^
  5803 |
  5804 |     function createCommonjsModule(fn) {
  5805 |       var module = { exports: {} };
    at Parser._raise (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:776:17)
    at Parser.raiseWithData (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:769:17)
    at Parser.raise (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:737:17)
    at Parser.unexpected (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:9668:16)
    at Parser.parseIdentifierName (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:11828:18)
    at Parser.parseIdentifier (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:11801:23)
    at Parser.parseFunctionId (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:12911:55)
    at Parser.parseFunction (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:12883:22)
    at Parser.parseFunctionStatement (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:12532:17)
    at Parser.parseStatementContent (/Users/u8915055/.homeassistant/www/mini-graph-card/node_modules/@babel/parser/lib/index.js:12222:21) {
  loc: Position { line: 5802, column: 12 },
  pos: 235073,
  code: 'BABEL_PARSE_ERROR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mini-graph-card@0.11.0-dev.4 babel: `babel dist/mini-graph-card-bundle.js --out-file dist/mini-graph-card-bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mini-graph-card@0.11.0-dev.4 babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/u8915055/.npm/_logs/2021-03-07T22_17_29_370Z-debug.log
npm ERR! code 1
npm ERR! path /Users/u8915055/.homeassistant/www/mini-graph-card
npm ERR! command failed
npm ERR! command sh -c npm run lint && npm run rollup && npm run babel

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/u8915055/.npm/_logs/2021-03-07T22_17_29_399Z-debug.log
```

Any idea what might be happening here?

Thanks very much.

**Comment by u8915055** [comment]
I wanted to update this.  I was able to get it working.  When i followed the instructions on the README page to do a git clone, git checkout dev, etc, for some reason i got a different, older set of resources, listed below:

```
mac-mini:mini-graph-card u8915055$ npm list
mini-graph-card@0.11.0-dev.4 /Users/u8915055/.homeassistant/www/mini-graph-card
├── @babel/cli@7.6.4
├── @babel/core@7.6.4
├── @babel/plugin-proposal-class-properties@7.3.3
├── @babel/plugin-proposal-decorators@7.3.0
├── @babel/plugin-proposal-object-rest-spread@7.3.4
├── @babel/plugin-transform-spread@7.2.2
├── @babel/plugin-transform-template-literals@7.2.0
├── @babel/preset-env@7.3.1
├── @kalkih/lz-string@1.4.5
├── @rollup/plugin-commonjs@17.1.0
├── @rollup/plugin-json@4.1.0
├── @semantic-release/changelog@5.0.1
├── @semantic-release/commit-analyzer@8.0.1
├── @semantic-release/exec@5.0.0
├── @semantic-release/git@9.0.0
├── @semantic-release/github@7.2.0
├── @semantic-release/npm@7.0.9
├── @semantic-release/release-notes-generator@9.0.1
├── @types/spark-md5@3.0.2
├── babel-plugin-iife-wrap@1.1.0
├── babel-preset-minify@0.5.0
├── custom-card-helpers@1.7.0
├── eslint-config-airbnb-base@13.2.0
├── eslint-plugin-import@2.22.1
├── eslint@5.16.0
├── lit-element@2.2.1
├── localforage@1.7.3
├── rollup-plugin-node-resolve@3.4.0
├── rollup-plugin-serve@1.1.0
├── rollup@2.40.0
├── semantic-release@17.4.1
└── spark-md5@3.0.1
```

However, when i deleted everything and tried again, i got the following set of resources, and the build worked with this set.

```
mini-graph-card@0.10.0 /Users/u8915055/.homeassistant/www/mini-graph-card
├── @babel/cli@7.12.10
├── @babel/core@7.12.10
├── @babel/plugin-proposal-class-properties@7.12.1
├── @babel/plugin-proposal-decorators@7.12.12
├── @babel/plugin-proposal-object-rest-spread@7.12.1
├── @babel/plugin-transform-spread@7.12.1
├── @babel/plugin-transform-template-literals@7.12.1
├── @babel/preset-env@7.12.11
├── @kalkih/lz-string@1.4.5
├── @rollup/plugin-json@4.1.0
├── @semantic-release/changelog@5.0.1
├── @semantic-release/commit-analyzer@8.0.1
├── @semantic-release/git@9.0.0
├── @semantic-release/github@7.2.0
├── @semantic-release/npm@7.0.9
├── @semantic-release/release-notes-generator@9.0.1
├── babel-plugin-iife-wrap@1.1.0
├── babel-preset-minify@0.5.1
├── eslint-config-airbnb-base@13.2.0
├── eslint-plugin-import@2.22.1
├── eslint@5.16.0
├── lit-element@2.4.0
├── localforage@1.9.0
├── rollup-plugin-node-resolve@3.4.0
├── rollup-plugin-serve@1.1.0
├── rollup@2.36.2
└── semantic-release@17.3.3
```

I dont know what i did differently but it seems to be working now.
